import { cn } from "@/lib/utils";

/** Brand logo generated by apps/api/scripts/gen-assets.ts */
export function Logo({
  variant = "light",
  className,
}: {
  variant?: "light" | "dark" | "mark";
  className?: string;
}) {
  const src =
    variant === "mark"
      ? "/favicon.svg"
      : variant === "dark"
        ? "/logo-dark.svg"
        : "/logo.svg";
  return (
    <img
      src={src}
      alt="Shimla Wale: Bhai Gurpreet Singh Ji"
      className={cn(variant === "mark" ? "size-10" : "h-11 w-auto", className)}
    />
  );
}
